name: "Main"

on: [push, pull_request]

jobs:
  package:
    runs-on: ubuntu-latest
    name: Package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "23"
      - run: yarn install
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install -g vsce
      - run: vsce package
      - id: vsix-path
        run: |
          echo "VSIX_PATH=$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)" >> $GITHUB_OUTPUT
          echo "VSIX_NAME=$(basename $(find . -maxdepth 1 -type f -iname "*.vsix" | head -1))" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.vsix-path.outputs.VSIX_PATH }}
          name: ${{ steps.vsix-path.outputs.VSIX_NAME }}
  release:
    runs-on: ubuntu-latest
    needs: package
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "23"
      - run: yarn install
      - run: npm install -g vsce
      - run: vsce package
      - id: get-vsix
        run: |
          echo "VSIX_PATH=$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)" >> $GITHUB_OUTPUT
          echo "VSIX_NAME=$(basename $(find . -maxdepth 1 -type f -iname "*.vsix" | head -1))" >> $GITHUB_OUTPUT
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: See [CHANGE LOG](https://github.com/murugaratham/vscode-dotnet-watch/blob/main/CHANGELOG.md) for details.
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-vsix.outputs.VSIX_PATH }}
          asset_name: ${{ steps.get-vsix.outputs.VSIX_NAME }}
          asset_content_type: application/zip
      - run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}
